### ISSUE TITLE
server/run: line 6: ../3rd/skynet/skynet: 没有那个文件或目录

### ISSUE THREAD

**Issue by kibozh** [jintiao/some-mmorpg#3]
执行server/run 命令时提示： server/run: line 6: ../3rd/skynet/skynet: 没有那个文件或目录，然而skynet我已经下载好并且编译了，请问这个问题怎么解决。  备注：第6行代码是 ../3rd/skynet/skynet config

**Comment by kibozh** [comment]
已解决

**Comment by Bellill** [comment]
> 已解决

这个怎么解决的

**Comment by kibozh** [comment]
> > 已解决
> 
> 这个怎么解决的

大佬，这都8年前了，早就不用这个skynet了，也忘了怎么解决的了。

**Comment by Bellill** [comment]
> > > 已解决
> > 
> > 
> > 这个怎么解决的
> 
> 大佬，这都八年前了，早就不用这个天网了，也忘了怎么解决的了。

已解决，make macos下就好

**Comment by kibozh** [comment]
> > > > 已解决
> > > 
> > > 
> > > 这个怎么解决的
> > 
> > 
> > 大佬，这都八年前了，早就不用这个天网了，也忘了怎么解决的了。
> 
> 已解决，make macos下就好

好咧，恭喜😄
